[2024-02-27T12:07:12.655+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-27T04:28:02.034457+00:00 [queued]>
[2024-02-27T12:07:12.681+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-27T04:28:02.034457+00:00 [queued]>
[2024-02-27T12:07:12.681+0700] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2024-02-27T12:07:12.713+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-27 04:28:02.034457+00:00
[2024-02-27T12:07:12.716+0700] {standard_task_runner.py:60} INFO - Started process 32216 to run task
[2024-02-27T12:07:12.728+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-27T04:28:02.034457+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpjamgytdq']
[2024-02-27T12:07:12.731+0700] {standard_task_runner.py:88} INFO - Job 156: Subtask spark_ingestion_to_s3
[2024-02-27T12:07:12.905+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-27T04:28:02.034457+00:00 [running]> on host MinhNhut.
[2024-02-27T12:07:13.314+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T04:28:02.034457+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-27T04:28:02.034457+00:00'
[2024-02-27T12:07:13.316+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T12:07:13.317+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-27T12:07:13.341+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:07:23.454+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-27T12:07:23.481+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-27T12:07:34.239+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-27T12:07:34.727+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-27T12:07:34.728+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-27T12:07:34.763+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-27T12:07:34.788+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a0f091b9-9d43-47fd-b80d-d857eb59f3fd;1.0
[2024-02-27T12:07:34.788+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:35.584+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-27T12:07:35.740+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-27T12:07:35.881+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-27T12:07:36.024+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 1204ms :: artifacts dl 54ms
[2024-02-27T12:07:36.024+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-27T12:07:36.025+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-27T12:07:36.025+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-27T12:07:36.026+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-27T12:07:36.026+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:36.027+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-27T12:07:36.027+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-27T12:07:36.028+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:36.028+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-27T12:07:36.029+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:36.069+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-a0f091b9-9d43-47fd-b80d-d857eb59f3fd
[2024-02-27T12:07:36.070+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:36.122+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/45ms)
[2024-02-27T12:07:37.471+0700] {subprocess.py:93} INFO - 24/02/27 12:07:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-27T12:07:38.882+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-27T12:07:38.883+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-27T12:07:45.124+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-02-27T12:07:45.128+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-02-27T12:07:45.144+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-02-27T12:07:45.145+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-02-27T12:07:45.172+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-02-27T12:07:45.176+0700] {subprocess.py:93} INFO - 24/02/27 12:07:45 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-02-27T12:08:01.651+0700] {subprocess.py:93} INFO - 24/02/27 12:08:01 ERROR Inbox: Ignoring error
[2024-02-27T12:08:01.659+0700] {subprocess.py:93} INFO - java.lang.NullPointerException
[2024-02-27T12:08:01.670+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:677)
[2024-02-27T12:08:01.670+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2024-02-27T12:08:01.670+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2024-02-27T12:08:01.671+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2024-02-27T12:08:01.671+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2024-02-27T12:08:01.671+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2024-02-27T12:08:01.676+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2024-02-27T12:08:01.676+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-02-27T12:08:01.676+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-02-27T12:08:01.677+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-27T12:08:01.677+0700] {subprocess.py:93} INFO - 24/02/27 12:08:01 WARN Executor: Issue communicating with driver in heartbeater
[2024-02-27T12:08:01.677+0700] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-02-27T12:08:01.677+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2024-02-27T12:08:01.678+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2024-02-27T12:08:01.679+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:677)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2024-02-27T12:08:01.680+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2024-02-27T12:08:01.681+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2024-02-27T12:08:01.681+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2024-02-27T12:08:01.681+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2024-02-27T12:08:01.681+0700] {subprocess.py:93} INFO - 	... 3 more
[2024-02-27T12:12:18.275+0700] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                24/02/27 12:12:18 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-02-27T12:13:00.515+0700] {subprocess.py:93} INFO - [Stage 1:>                                                          (0 + 4) / 4]ERROR:root:Exception while sending command.
[2024-02-27T12:13:00.563+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:00.563+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
[2024-02-27T12:13:00.569+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2024-02-27T12:13:00.569+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-02-27T12:13:00.570+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:13:00.570+0700] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-02-27T12:13:00.570+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:13:00.570+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:00.571+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2024-02-27T12:13:00.571+0700] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2024-02-27T12:13:00.571+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
[2024-02-27T12:13:00.572+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2024-02-27T12:13:00.572+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-02-27T12:13:00.573+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:00.573+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 31, in <module>
[2024-02-27T12:13:00.574+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-27T12:13:00.577+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 27, in extract_data
[2024-02-27T12:13:00.578+0700] {subprocess.py:93} INFO -     df.write.mode("overwrite").parquet("s3a://olistsalesbucket/" + name_file + ".parquet")
[2024-02-27T12:13:00.578+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2024-02-27T12:13:00.579+0700] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2024-02-27T12:13:00.579+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-27T12:13:00.580+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-27T12:13:00.580+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-27T12:13:00.580+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-27T12:13:00.581+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 334, in get_return_value
[2024-02-27T12:13:00.581+0700] {subprocess.py:93} INFO -     raise Py4JError(
[2024-02-27T12:13:00.584+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o35.parquet
[2024-02-27T12:13:00.783+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-27T12:13:01.769+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-27T12:13:01.906+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240227T042802, start_date=20240227T050712, end_date=20240227T051301
[2024-02-27T12:13:03.172+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 156 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 32216)
[2024-02-27T12:13:03.220+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T12:13:03.675+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
