[2024-02-26T18:26:03.402+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-26T18:26:03.418+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-26T18:26:03.419+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T18:26:03.459+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:18:08.120077+00:00
[2024-02-26T18:26:03.466+0700] {standard_task_runner.py:60} INFO - Started process 26060 to run task
[2024-02-26T18:26:03.474+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:18:08.120077+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp8cv6vwcv']
[2024-02-26T18:26:03.481+0700] {standard_task_runner.py:88} INFO - Job 83: Subtask spark_ingestion_to_s3
[2024-02-26T18:26:03.675+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [running]> on host MinhNhut.
[2024-02-26T18:26:03.971+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:18:08.120077+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:18:08.120077+00:00'
[2024-02-26T18:26:03.973+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T18:26:03.974+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-26T18:26:03.991+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T18:26:09.006+0700] {subprocess.py:93} INFO - 24/02/26 18:26:09 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-26T18:26:09.010+0700] {subprocess.py:93} INFO - 24/02/26 18:26:09 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-26T18:26:20.055+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-26T18:26:20.462+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-26T18:26:20.462+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-26T18:26:20.511+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-26T18:26:20.514+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-16971be1-6b51-413b-9a87-0a7fc27d7940;1.0
[2024-02-26T18:26:20.515+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:26:21.411+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-26T18:26:21.532+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-26T18:26:21.697+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-26T18:26:21.856+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 1291ms :: artifacts dl 34ms
[2024-02-26T18:26:21.858+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-26T18:26:21.861+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-26T18:26:21.862+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-26T18:26:21.863+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-26T18:26:21.864+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:26:21.865+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-26T18:26:21.867+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-26T18:26:21.868+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:26:21.875+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-26T18:26:21.879+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-26T18:26:21.891+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:26:21.892+0700] {subprocess.py:93} INFO - :: problems summary ::
[2024-02-26T18:26:21.893+0700] {subprocess.py:93} INFO - :::: ERRORS
[2024-02-26T18:26:21.893+0700] {subprocess.py:93} INFO - 	unknown resolver null
[2024-02-26T18:26:21.894+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:26:21.894+0700] {subprocess.py:93} INFO - 	unknown resolver null
[2024-02-26T18:26:21.894+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:26:21.894+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:26:21.895+0700] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-02-26T18:26:21.895+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-16971be1-6b51-413b-9a87-0a7fc27d7940
[2024-02-26T18:26:21.895+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-26T18:26:21.922+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/29ms)
[2024-02-26T18:26:22.908+0700] {subprocess.py:93} INFO - 24/02/26 18:26:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-26T18:26:23.619+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-26T18:26:23.620+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-26T18:26:26.668+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-02-26T18:26:26.673+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-02-26T18:26:26.675+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-02-26T18:26:26.680+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-02-26T18:26:26.682+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-02-26T18:26:26.685+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-02-26T18:26:26.687+0700] {subprocess.py:93} INFO - 24/02/26 18:26:26 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-02-26T18:26:59.358+0700] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                24/02/26 18:26:59 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-02-26T18:27:34.211+0700] {subprocess.py:93} INFO - [Stage 1:>                                                          (0 + 1) / 1]ERROR:root:Exception while sending command.
[2024-02-26T18:27:34.220+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-26T18:27:34.220+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
[2024-02-26T18:27:34.240+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2024-02-26T18:27:34.241+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-02-26T18:27:34.241+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:27:34.241+0700] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-02-26T18:27:34.242+0700] {subprocess.py:93} INFO - 
[2024-02-26T18:27:34.242+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-26T18:27:34.242+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2024-02-26T18:27:34.242+0700] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2024-02-26T18:27:34.243+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
[2024-02-26T18:27:34.243+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2024-02-26T18:27:34.253+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-02-26T18:27:34.254+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-26T18:27:34.255+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 28, in <module>
[2024-02-26T18:27:34.255+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-26T18:27:34.263+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 25, in extract_data
[2024-02-26T18:27:34.264+0700] {subprocess.py:93} INFO -     df.coalesce(1).write.mode("append").parquet("s3a://olistsalesbucket/" + name_file + ".parquet")
[2024-02-26T18:27:34.266+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2024-02-26T18:27:34.266+0700] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2024-02-26T18:27:34.271+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-26T18:27:34.271+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-26T18:27:34.272+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-26T18:27:34.272+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-26T18:27:34.287+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 334, in get_return_value
[2024-02-26T18:27:34.287+0700] {subprocess.py:93} INFO -     raise Py4JError(
[2024-02-26T18:27:34.288+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o41.parquet
[2024-02-26T18:27:35.469+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-26T18:27:37.940+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-26T18:27:38.000+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T091808, start_date=20240226T112603, end_date=20240226T112737
[2024-02-26T18:27:38.339+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 26060)
[2024-02-26T18:27:38.379+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T18:27:38.631+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
