[2024-02-27T12:07:12.472+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-27T12:07:12.493+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-27T12:07:12.493+0700] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-27T12:07:12.537+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:18:08.120077+00:00
[2024-02-27T12:07:12.541+0700] {standard_task_runner.py:60} INFO - Started process 32140 to run task
[2024-02-27T12:07:12.547+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:18:08.120077+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpx1h845zn']
[2024-02-27T12:07:12.552+0700] {standard_task_runner.py:88} INFO - Job 146: Subtask spark_ingestion_to_s3
[2024-02-27T12:07:12.718+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:18:08.120077+00:00 [running]> on host MinhNhut.
[2024-02-27T12:07:13.008+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:18:08.120077+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:18:08.120077+00:00'
[2024-02-27T12:07:13.011+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T12:07:13.012+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-27T12:07:13.030+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:07:22.407+0700] {subprocess.py:93} INFO - 24/02/27 12:07:22 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-27T12:07:22.436+0700] {subprocess.py:93} INFO - 24/02/27 12:07:22 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-27T12:07:32.596+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-27T12:07:32.672+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-27T12:07:32.673+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-27T12:07:32.678+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-27T12:07:32.678+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-24b663aa-60be-4f3d-8c7e-d53f0c477a3e;1.0
[2024-02-27T12:07:32.679+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:32.797+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-27T12:07:32.821+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-27T12:07:32.840+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-27T12:07:32.858+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 172ms :: artifacts dl 8ms
[2024-02-27T12:07:32.858+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-27T12:07:32.859+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:32.860+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-27T12:07:32.860+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:32.861+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-24b663aa-60be-4f3d-8c7e-d53f0c477a3e
[2024-02-27T12:07:32.862+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:32.866+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/5ms)
[2024-02-27T12:07:33.051+0700] {subprocess.py:93} INFO - 24/02/27 12:07:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-27T12:07:33.294+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-27T12:07:33.294+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-27T12:10:59.126+0700] {subprocess.py:93} INFO - ERROR:root:Exception while sending command.
[2024-02-27T12:10:59.434+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:10:59.435+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
[2024-02-27T12:10:59.449+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2024-02-27T12:10:59.449+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-02-27T12:10:59.450+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:10:59.450+0700] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-02-27T12:10:59.450+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:10:59.450+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:10:59.451+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2024-02-27T12:10:59.451+0700] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2024-02-27T12:10:59.451+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
[2024-02-27T12:10:59.451+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2024-02-27T12:10:59.453+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-02-27T12:10:59.454+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:10:59.455+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 31, in <module>
[2024-02-27T12:10:59.455+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-27T12:10:59.463+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 23, in extract_data
[2024-02-27T12:10:59.465+0700] {subprocess.py:93} INFO -     df = spark.read.csv(csv_file, header= True)
[2024-02-27T12:10:59.465+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 740, in csv
[2024-02-27T12:10:59.465+0700] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2024-02-27T12:10:59.466+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-27T12:10:59.466+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-27T12:10:59.466+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-27T12:10:59.467+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-27T12:10:59.472+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 334, in get_return_value
[2024-02-27T12:10:59.473+0700] {subprocess.py:93} INFO -     raise Py4JError(
[2024-02-27T12:10:59.473+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o30.csv
[2024-02-27T12:10:59.664+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-27T12:11:01.771+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-27T12:11:01.930+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T091808, start_date=20240227T050712, end_date=20240227T051101
[2024-02-27T12:11:05.818+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 32140)
[2024-02-27T12:11:06.837+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T12:11:17.282+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
