[2024-02-27T10:49:36.331+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-27T10:49:36.338+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job scheduled__2024-02-26T00:00:00+00:00 [queued]>
[2024-02-27T10:49:36.338+0700] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-02-27T10:49:36.351+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_transform_missed_deadline_job> on 2024-02-26 00:00:00+00:00
[2024-02-27T10:49:36.353+0700] {standard_task_runner.py:60} INFO - Started process 15918 to run task
[2024-02-27T10:49:36.355+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_transform_missed_deadline_job', 'scheduled__2024-02-26T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpou2yacv2']
[2024-02-27T10:49:36.357+0700] {standard_task_runner.py:88} INFO - Job 105: Subtask spark_transform_missed_deadline_job
[2024-02-27T10:49:36.413+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_transform_missed_deadline_job scheduled__2024-02-26T00:00:00+00:00 [running]> on host MinhNhut.
[2024-02-27T10:49:36.494+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_transform_missed_deadline_job' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T00:00:00+00:00'
[2024-02-27T10:49:36.495+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T10:49:36.496+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/nhut/etl-***/pipeline/spark_missed_deadline_job.py']
[2024-02-27T10:49:36.501+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T10:53:19.063+0700] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-27T10:53:19.067+0700] {process_utils.py:131} INFO - Sending 15 to group 15918. PIDs of all processes in the group: [15926, 15927, 15918]
[2024-02-27T10:53:19.067+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 15918
[2024-02-27T10:53:19.068+0700] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-27T10:53:19.068+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-02-27T10:53:19.120+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=15926, status='terminated', started='10:49:36') (15926) terminated with exit code None
[2024-02-27T10:53:19.121+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=15927, status='terminated', started='10:49:36') (15927) terminated with exit code None
[2024-02-27T10:53:19.121+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=15918, status='terminated', exitcode=0, started='10:49:36') (15918) terminated with exit code 0
