[2024-02-26T16:18:08.830+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-26T16:18:08.837+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:18:08.120077+00:00 [queued]>
[2024-02-26T16:18:08.838+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T16:18:08.849+0700] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_missed_deadline_table> on 2024-02-26 09:18:08.120077+00:00
[2024-02-26T16:18:08.851+0700] {standard_task_runner.py:60} INFO - Started process 14773 to run task
[2024-02-26T16:18:08.854+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'create_missed_deadline_table', 'manual__2024-02-26T09:18:08.120077+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpmjana5k2']
[2024-02-26T16:18:08.856+0700] {standard_task_runner.py:88} INFO - Job 45: Subtask create_missed_deadline_table
[2024-02-26T16:18:08.911+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:18:08.120077+00:00 [running]> on host MinhNhut.
[2024-02-26T16:18:08.956+0700] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'create_missed_deadline_table', field 'sql'. Template: 'sql/init_tb_olist_missed_deadline_job.sql'
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/init_tb_olist_missed_deadline_job.sql
[2024-02-26T16:18:08.958+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/init_tb_olist_missed_deadline_job.sql
[2024-02-26T16:18:08.970+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=create_missed_deadline_table, execution_date=20240226T091808, start_date=20240226T091808, end_date=20240226T091808
[2024-02-26T16:18:08.981+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task create_missed_deadline_table (sql/init_tb_olist_missed_deadline_job.sql; 14773)
[2024-02-26T16:18:08.987+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T16:18:09.014+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
