[2024-02-26T18:20:31.134+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [queued]>
[2024-02-26T18:20:31.141+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [queued]>
[2024-02-26T18:20:31.141+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T18:20:31.152+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 11:20:29.138176+00:00
[2024-02-26T18:20:31.154+0700] {standard_task_runner.py:60} INFO - Started process 20652 to run task
[2024-02-26T18:20:31.156+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T11:20:29.138176+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmprl2nh8my']
[2024-02-26T18:20:31.158+0700] {standard_task_runner.py:88} INFO - Job 64: Subtask spark_ingestion_to_s3
[2024-02-26T18:20:31.208+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T11:20:29.138176+00:00 [running]> on host MinhNhut.
[2024-02-26T18:20:31.289+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T11:20:29.138176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T11:20:29.138176+00:00'
[2024-02-26T18:20:31.290+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T18:20:31.290+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-26T18:20:31.294+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T18:20:31.449+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-26T18:20:31.449+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 5, in <module>
[2024-02-26T18:20:31.450+0700] {subprocess.py:93} INFO -     from spark import spark
[2024-02-26T18:20:31.450+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark/__init__.py", line 1, in <module>
[2024-02-26T18:20:31.450+0700] {subprocess.py:93} INFO -     from .spark_init import spark
[2024-02-26T18:20:31.451+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark/spark_init.py", line 5, in <module>
[2024-02-26T18:20:31.451+0700] {subprocess.py:93} INFO -     spark = spark_config.spark_init(access_id, access_key)
[2024-02-26T18:20:31.451+0700] {subprocess.py:93} INFO - AttributeError: module 'spark.spark_config' has no attribute 'spark_init'
[2024-02-26T18:20:31.477+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-26T18:20:31.491+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-26T18:20:31.494+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T112029, start_date=20240226T112031, end_date=20240226T112031
[2024-02-26T18:20:31.504+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 64 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 20652)
[2024-02-26T18:20:31.529+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T18:20:31.548+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
