[2024-02-26T16:22:33.101+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:22:32.166789+00:00 [queued]>
[2024-02-26T16:22:33.109+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:22:32.166789+00:00 [queued]>
[2024-02-26T16:22:33.110+0700] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T16:22:33.122+0700] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_missed_deadline_table> on 2024-02-26 09:22:32.166789+00:00
[2024-02-26T16:22:33.124+0700] {standard_task_runner.py:60} INFO - Started process 20651 to run task
[2024-02-26T16:22:33.127+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'create_missed_deadline_table', 'manual__2024-02-26T09:22:32.166789+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmpno_tj8im']
[2024-02-26T16:22:33.129+0700] {standard_task_runner.py:88} INFO - Job 47: Subtask create_missed_deadline_table
[2024-02-26T16:22:33.209+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.create_missed_deadline_table manual__2024-02-26T09:22:32.166789+00:00 [running]> on host MinhNhut.
[2024-02-26T16:22:33.293+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='create_missed_deadline_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:22:32.166789+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:22:32.166789+00:00'
[2024-02-26T16:22:33.293+0700] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS olist_missed_deadline_tb(
    id SERIAL,
    order_id VARCHAR(200),
    seller_id VARCHAR(200),
    shipping_limit_date DATETIME,
    price FLOAT,
    freight_value, FLOAT,
    product_id VARCHAR(200),
    product_category_name VARCHAR(200),
    customer_id VARCHAR(200),
    order_status VARCHAR(200),
    order_purchase_timestamp DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATETIME,
    PRIMARY KEY (id, order_id, seller_id, product_id)
);
[2024-02-26T16:22:33.319+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `olist_pg_conn` isn't defined
[2024-02-26T16:22:33.325+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=create_missed_deadline_table, execution_date=20240226T092232, start_date=20240226T092233, end_date=20240226T092233
[2024-02-26T16:22:33.336+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task create_missed_deadline_table (The conn_id `olist_pg_conn` isn't defined; 20651)
[2024-02-26T16:22:33.379+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T16:22:33.403+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
