[2024-02-27T12:07:12.524+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:27:10.724567+00:00 [queued]>
[2024-02-27T12:07:12.545+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:27:10.724567+00:00 [queued]>
[2024-02-27T12:07:12.545+0700] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-27T12:07:12.591+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:27:10.724567+00:00
[2024-02-27T12:07:12.597+0700] {standard_task_runner.py:60} INFO - Started process 32161 to run task
[2024-02-27T12:07:12.601+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:27:10.724567+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp35eh0nfp']
[2024-02-27T12:07:12.605+0700] {standard_task_runner.py:88} INFO - Job 150: Subtask spark_ingestion_to_s3
[2024-02-27T12:07:12.792+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:27:10.724567+00:00 [running]> on host MinhNhut.
[2024-02-27T12:07:13.027+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:27:10.724567+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:27:10.724567+00:00'
[2024-02-27T12:07:13.029+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T12:07:13.030+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-27T12:07:13.046+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:07:23.854+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-27T12:07:23.874+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-27T12:07:35.370+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-27T12:07:35.771+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-27T12:07:35.772+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-27T12:07:35.804+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-27T12:07:35.811+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-317b3143-e8d2-4c1c-b3b8-63d8bc4a98d2;1.0
[2024-02-27T12:07:35.812+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:36.652+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-27T12:07:36.805+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-27T12:07:37.004+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-27T12:07:37.105+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 1263ms :: artifacts dl 35ms
[2024-02-27T12:07:37.105+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-27T12:07:37.106+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-27T12:07:37.107+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-27T12:07:37.107+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-27T12:07:37.108+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.108+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-27T12:07:37.109+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-27T12:07:37.109+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.109+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-27T12:07:37.110+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.141+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-317b3143-e8d2-4c1c-b3b8-63d8bc4a98d2
[2024-02-27T12:07:37.142+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:37.174+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/31ms)
[2024-02-27T12:07:38.527+0700] {subprocess.py:93} INFO - 24/02/27 12:07:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-27T12:07:39.740+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-27T12:07:39.740+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-27T12:07:46.389+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-02-27T12:07:46.440+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-02-27T12:07:46.440+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-02-27T12:07:46.441+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-02-27T12:07:46.441+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-02-27T12:07:46.442+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-02-27T12:07:46.444+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-02-27T12:07:46.454+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-02-27T12:07:46.454+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2024-02-27T12:07:46.455+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2024-02-27T12:07:46.455+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2024-02-27T12:07:46.455+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
[2024-02-27T12:07:46.456+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
[2024-02-27T12:08:04.732+0700] {subprocess.py:93} INFO - 24/02/27 12:08:04 ERROR Inbox: Ignoring error
[2024-02-27T12:08:04.733+0700] {subprocess.py:93} INFO - java.lang.NullPointerException
[2024-02-27T12:08:04.733+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:677)
[2024-02-27T12:08:04.734+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2024-02-27T12:08:04.734+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2024-02-27T12:08:04.734+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2024-02-27T12:08:04.734+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2024-02-27T12:08:04.735+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2024-02-27T12:08:04.735+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2024-02-27T12:08:04.735+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-02-27T12:08:04.736+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-02-27T12:08:04.737+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-27T12:08:04.738+0700] {subprocess.py:93} INFO - 24/02/27 12:08:04 WARN Executor: Issue communicating with driver in heartbeater
[2024-02-27T12:08:04.738+0700] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-02-27T12:08:04.738+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-02-27T12:08:04.738+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-02-27T12:08:04.739+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-02-27T12:08:04.739+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2024-02-27T12:08:04.739+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
[2024-02-27T12:08:04.739+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
[2024-02-27T12:08:04.740+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
[2024-02-27T12:08:04.740+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
[2024-02-27T12:08:04.740+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
[2024-02-27T12:08:04.741+0700] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-02-27T12:08:04.741+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
[2024-02-27T12:08:04.741+0700] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2024-02-27T12:08:04.742+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-02-27T12:08:04.742+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2024-02-27T12:08:04.744+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2024-02-27T12:08:04.745+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-02-27T12:08:04.745+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-02-27T12:08:04.745+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-27T12:08:04.746+0700] {subprocess.py:93} INFO - Caused by: java.lang.NullPointerException
[2024-02-27T12:08:04.746+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:677)
[2024-02-27T12:08:04.746+0700] {subprocess.py:93} INFO - 	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
[2024-02-27T12:08:04.746+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
[2024-02-27T12:08:04.747+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
[2024-02-27T12:08:04.747+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
[2024-02-27T12:08:04.747+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
[2024-02-27T12:08:04.747+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
[2024-02-27T12:08:04.748+0700] {subprocess.py:93} INFO - 	... 3 more
[2024-02-27T12:12:39.999+0700] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                24/02/27 12:12:39 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-02-27T12:13:24.982+0700] {subprocess.py:93} INFO - [Stage 1:>                                                          (0 + 4) / 4]ERROR:root:Exception while sending command.
[2024-02-27T12:13:25.098+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:25.098+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
[2024-02-27T12:13:25.119+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2024-02-27T12:13:25.119+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-02-27T12:13:25.120+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:13:25.120+0700] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-02-27T12:13:25.120+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:13:25.120+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:25.120+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2024-02-27T12:13:25.121+0700] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2024-02-27T12:13:25.121+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
[2024-02-27T12:13:25.121+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2024-02-27T12:13:25.125+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-02-27T12:13:25.125+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:13:25.126+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 31, in <module>
[2024-02-27T12:13:25.126+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-27T12:13:25.126+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 27, in extract_data
[2024-02-27T12:13:25.126+0700] {subprocess.py:93} INFO -     df.write.mode("overwrite").parquet("s3a://olistsalesbucket/" + name_file + ".parquet")
[2024-02-27T12:13:25.127+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2024-02-27T12:13:25.127+0700] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2024-02-27T12:13:25.129+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-27T12:13:25.134+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-27T12:13:25.140+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-27T12:13:25.141+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-27T12:13:25.142+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 334, in get_return_value
[2024-02-27T12:13:25.143+0700] {subprocess.py:93} INFO -     raise Py4JError(
[2024-02-27T12:13:25.145+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o35.parquet
[2024-02-27T12:13:26.560+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-27T12:13:27.548+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-27T12:13:27.619+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T092710, start_date=20240227T050712, end_date=20240227T051327
[2024-02-27T12:13:27.992+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 150 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 32161)
[2024-02-27T12:13:28.019+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T12:13:28.250+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
