[2024-02-26T16:37:09.024+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-26T16:37:09.030+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-26T16:37:09.031+0700] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-26T16:37:09.042+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:32:23.006143+00:00
[2024-02-26T16:37:09.044+0700] {standard_task_runner.py:60} INFO - Started process 38809 to run task
[2024-02-26T16:37:09.046+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:32:23.006143+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp9_lgaexd']
[2024-02-26T16:37:09.048+0700] {standard_task_runner.py:88} INFO - Job 59: Subtask spark_ingestion_to_s3
[2024-02-26T16:37:09.099+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [running]> on host MinhNhut.
[2024-02-26T16:37:09.177+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:32:23.006143+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:32:23.006143+00:00'
[2024-02-26T16:37:09.178+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-26T16:37:09.179+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python ***/dags/pipeline/spark_ingestion_to_s3.py']
[2024-02-26T16:37:09.183+0700] {subprocess.py:86} INFO - Output:
[2024-02-26T16:37:09.200+0700] {subprocess.py:93} INFO - python: can't open file '/tmp/***tmpalj96kw9/***/dags/pipeline/spark_ingestion_to_s3.py': [Errno 2] No such file or directory
[2024-02-26T16:37:09.203+0700] {subprocess.py:97} INFO - Command exited with return code 2
[2024-02-26T16:37:09.217+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-02-26T16:37:09.219+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T093223, start_date=20240226T093709, end_date=20240226T093709
[2024-02-26T16:37:09.229+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 38809)
[2024-02-26T16:37:09.259+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-26T16:37:09.277+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
