[2024-02-27T12:07:12.507+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-27T12:07:12.522+0700] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [queued]>
[2024-02-27T12:07:12.522+0700] {taskinstance.py:2170} INFO - Starting attempt 7 of 7
[2024-02-27T12:07:12.577+0700] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): spark_ingestion_to_s3> on 2024-02-26 09:32:23.006143+00:00
[2024-02-27T12:07:12.581+0700] {standard_task_runner.py:60} INFO - Started process 32155 to run task
[2024-02-27T12:07:12.589+0700] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'missed_deadline_job_dag', 'spark_ingestion_to_s3', 'manual__2024-02-26T09:32:23.006143+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/missed_deadlinee_dag.py', '--cfg-path', '/tmp/tmp4d68ft7v']
[2024-02-27T12:07:12.593+0700] {standard_task_runner.py:88} INFO - Job 151: Subtask spark_ingestion_to_s3
[2024-02-27T12:07:12.785+0700] {task_command.py:423} INFO - Running <TaskInstance: missed_deadline_job_dag.spark_ingestion_to_s3 manual__2024-02-26T09:32:23.006143+00:00 [running]> on host MinhNhut.
[2024-02-27T12:07:13.146+0700] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='missed_deadline_job_dag' AIRFLOW_CTX_TASK_ID='spark_ingestion_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T09:32:23.006143+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-26T09:32:23.006143+00:00'
[2024-02-27T12:07:13.150+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-27T12:07:13.151+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py']
[2024-02-27T12:07:13.172+0700] {subprocess.py:86} INFO - Output:
[2024-02-27T12:07:23.836+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Your hostname, MinhNhut resolves to a loopback address: 127.0.1.1; using 172.28.89.67 instead (on interface eth0)
[2024-02-27T12:07:23.855+0700] {subprocess.py:93} INFO - 24/02/27 12:07:23 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-02-27T12:07:34.881+0700] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-02-27T12:07:35.375+0700] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/nhut/.ivy2/cache
[2024-02-27T12:07:35.376+0700] {subprocess.py:93} INFO - The jars for the packages stored in: /home/nhut/.ivy2/jars
[2024-02-27T12:07:35.458+0700] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-02-27T12:07:35.459+0700] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-98e65601-b99d-4376-8cb9-b2eb40d66ca5;1.0
[2024-02-27T12:07:35.460+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:36.465+0700] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.2 in spark-list
[2024-02-27T12:07:36.606+0700] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.1026 in spark-list
[2024-02-27T12:07:36.818+0700] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-02-27T12:07:37.033+0700] {subprocess.py:93} INFO - :: resolution report :: resolve 1509ms :: artifacts dl 52ms
[2024-02-27T12:07:37.034+0700] {subprocess.py:93} INFO - 	:: modules in use:
[2024-02-27T12:07:37.039+0700] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.1026 from spark-list in [default]
[2024-02-27T12:07:37.041+0700] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.2 from spark-list in [default]
[2024-02-27T12:07:37.044+0700] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-02-27T12:07:37.045+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.046+0700] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-02-27T12:07:37.047+0700] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-02-27T12:07:37.048+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.049+0700] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-02-27T12:07:37.052+0700] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-02-27T12:07:37.076+0700] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-98e65601-b99d-4376-8cb9-b2eb40d66ca5
[2024-02-27T12:07:37.077+0700] {subprocess.py:93} INFO - 	confs: [default]
[2024-02-27T12:07:37.102+0700] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/11ms)
[2024-02-27T12:07:38.304+0700] {subprocess.py:93} INFO - 24/02/27 12:07:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-02-27T12:07:39.533+0700] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-02-27T12:07:39.534+0700] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-02-27T12:07:46.309+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-02-27T12:07:46.317+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-02-27T12:07:46.323+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-02-27T12:07:46.323+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-02-27T12:07:46.323+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-02-27T12:07:46.324+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-02-27T12:07:46.324+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-02-27T12:07:46.326+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2024-02-27T12:07:46.328+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2024-02-27T12:07:46.328+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2024-02-27T12:07:46.329+0700] {subprocess.py:93} INFO - 24/02/27 12:07:46 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2024-02-27T12:10:58.917+0700] {subprocess.py:93} INFO - 24/02/27 12:10:58 WARN NettyRpcEnv: Ignored message: HeartbeatResponse(false)
[2024-02-27T12:10:59.082+0700] {subprocess.py:93} INFO - 24/02/27 12:10:58 WARN Executor: Issue communicating with driver in heartbeater
[2024-02-27T12:10:59.083+0700] {subprocess.py:93} INFO - org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10000 milliseconds]. This timeout is controlled by spark.executor.heartbeatInterval
[2024-02-27T12:10:59.083+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
[2024-02-27T12:10:59.084+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
[2024-02-27T12:10:59.084+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
[2024-02-27T12:10:59.085+0700] {subprocess.py:93} INFO - 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[2024-02-27T12:10:59.085+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
[2024-02-27T12:10:59.085+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
[2024-02-27T12:10:59.086+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1219)
[2024-02-27T12:10:59.086+0700] {subprocess.py:93} INFO - 	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
[2024-02-27T12:10:59.087+0700] {subprocess.py:93} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2024-02-27T12:10:59.087+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
[2024-02-27T12:10:59.087+0700] {subprocess.py:93} INFO - 	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
[2024-02-27T12:10:59.088+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2024-02-27T12:10:59.088+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2024-02-27T12:10:59.088+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2024-02-27T12:10:59.088+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[2024-02-27T12:10:59.089+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:48)
[2024-02-27T12:10:59.090+0700] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-02-27T12:10:59.090+0700] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-02-27T12:10:59.090+0700] {subprocess.py:93} INFO - 	... 12 more
[2024-02-27T12:12:38.054+0700] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                24/02/27 12:12:38 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-02-27T12:12:55.921+0700] {subprocess.py:93} INFO - ERROR:root:Exception while sending command.
[2024-02-27T12:12:55.984+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:12:55.986+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 516, in send_command
[2024-02-27T12:12:55.997+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2024-02-27T12:12:55.997+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2024-02-27T12:12:55.998+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:12:55.998+0700] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2024-02-27T12:12:56.000+0700] {subprocess.py:93} INFO - 
[2024-02-27T12:12:56.001+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:12:56.002+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2024-02-27T12:12:56.006+0700] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2024-02-27T12:12:56.007+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/clientserver.py", line 539, in send_command
[2024-02-27T12:12:56.014+0700] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2024-02-27T12:12:56.015+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2024-02-27T12:12:56.018+0700] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-27T12:12:56.024+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 31, in <module>
[2024-02-27T12:12:56.026+0700] {subprocess.py:93} INFO -     extract_data()
[2024-02-27T12:12:56.027+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/pipeline/spark_ingestion_to_s3.py", line 27, in extract_data
[2024-02-27T12:12:56.038+0700] {subprocess.py:93} INFO -     df.write.mode("overwrite").parquet("s3a://olistsalesbucket/" + name_file + ".parquet")
[2024-02-27T12:12:56.039+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
[2024-02-27T12:12:56.041+0700] {subprocess.py:93} INFO -     self._jwrite.parquet(path)
[2024-02-27T12:12:56.042+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-02-27T12:12:56.043+0700] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-02-27T12:12:56.044+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-02-27T12:12:56.045+0700] {subprocess.py:93} INFO -     return f(*a, **kw)
[2024-02-27T12:12:56.046+0700] {subprocess.py:93} INFO -   File "/home/nhut/etl-***/.venv/lib/python3.10/site-packages/py4j/protocol.py", line 334, in get_return_value
[2024-02-27T12:12:56.052+0700] {subprocess.py:93} INFO -     raise Py4JError(
[2024-02-27T12:12:56.053+0700] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o35.parquet
[2024-02-27T12:12:56.410+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-27T12:12:57.390+0700] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nhut/etl-airflow/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-27T12:12:57.572+0700] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=missed_deadline_job_dag, task_id=spark_ingestion_to_s3, execution_date=20240226T093223, start_date=20240227T050712, end_date=20240227T051257
[2024-02-27T12:12:57.990+0700] {standard_task_runner.py:107} ERROR - Failed to execute job 151 for task spark_ingestion_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 32155)
[2024-02-27T12:12:58.069+0700] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T12:12:58.774+0700] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
